requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Pricing*
  ignore:
    - Pricing::Configuration*
    - Pricing::Test*
    - Pricing::OnCalculateTotalValue#call
    - Pricing::OnCalculateTotalValue#calculate_sub_amounts