version: "3.2"
volumes:
  gems:
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=cqrs-es-sample-with-res
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"