requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Invoicing*
  ignore:
    - Invoicing::Configuration*
    - Invoicing::Test*
    - Invoicing::InvoiceItemTitleCatalog*
    - Invoicing::InvoiceService#initialize
    - Invoicing::FakeConcurrentInvoiceNumberGenerator#next_number