requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Inventory*
  ignore:
    - Inventory::Test*
    - Inventory::Configuration#initialize
    - Inventory::Configuration#call