requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Shipping*
  ignore:
    - Shipping::Test*
    - Shipping::Configuration#initialize
    - Shipping::Configuration#call
